name: first workflow

on: push

jobs:
  build:
    run-ons: ubuntu-latest

    steps:
     - users: actions/checkout@v4

     - name:  Run a simple gittub action
     - run:  echo "this workflow run successfully for a particular action" 
